import { Home, Settings, ChevronRight } from 'lucide-react';

export default function HomePage() {
  return (
    <div className="min-h-screen bg-gray-100">
      <div className="container mx-auto px-4 py-8">
        <div className="max-w-4xl mx-auto">
          <header className="mb-8">
            <div className="flex items-center space-x-2 mb-4">
              <Home size={32} className="text-blue-600" />
              <h1 className="text-3xl font-bold text-gray-900">
                Welcome to Your Next.js App
              </h1>
            </div>
            <p className="text-lg text-gray-600">
              This is a Next.js application generated by AI with proper icon imports.
            </p>
          </header>

          <main className="space-y-6">
            <div className="bg-white rounded-lg shadow-md p-6">
              <div className="flex items-center justify-between mb-4">
                <h2 className="text-xl font-semibold text-gray-800">
                  Application Features
                </h2>
                <Settings size={24} className="text-gray-500" />
              </div>
              
              <ul className="space-y-3">
                <li className="flex items-center space-x-3">
                  <ChevronRight size={16} className="text-green-500" />
                  <span className="text-gray-700">Modern Next.js 14 Framework</span>
                </li>
                <li className="flex items-center space-x-3">
                  <ChevronRight size={16} className="text-green-500" />
                  <span className="text-gray-700">Tailwind CSS for Styling</span>
                </li>
                <li className="flex items-center space-x-3">
                  <ChevronRight size={16} className="text-green-500" />
                  <span className="text-gray-700">Lucide React Icons (Properly Imported)</span>
                </li>
                <li className="flex items-center space-x-3">
                  <ChevronRight size={16} className="text-green-500" />
                  <span className="text-gray-700">Responsive Design</span>
                </li>
              </ul>
            </div>

            <div className="bg-white rounded-lg shadow-md p-6">
              <h3 className="text-lg font-semibold text-gray-800 mb-3">
                Getting Started
              </h3>
              <p className="text-gray-600">
                Edit <code className="bg-gray-100 px-2 py-1 rounded text-sm">pages/index.js</code> to customize this page.
                All icons are properly imported from lucide-react to prevent build errors.
              </p>
            </div>
          </main>
        </div>
      </div>
    </div>
  );
}